name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: make install
    
    - name: Test server
      run: |
        make run & sleep 5
        curl -f http://localhost:5050 || echo "Server not running"
        kill $(lsof -t -i:5050) || echo "No server to kill"
